# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QSize, Qt,  QCoreApplication
from PyQt5.QtGui import QIcon


class Ui_weather_form(object):
    def setupUi(self, weather_form):
        weather_form.setWindowFlags(Qt.FramelessWindowHint)
        weather_form.setWindowTitle('Погода Fejo')
        weather_form.setObjectName("weather_form")
        weather_form.resize(371, 440)
        weather_form.setTabletTracking(True)
        weather_form.setFocusPolicy(QtCore.Qt.ClickFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../76818-forecasting-material-rain-shower-weather-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        weather_form.setWindowIcon(icon)
        weather_form.setWindowOpacity(1.0)
        weather_form.setLayoutDirection(QtCore.Qt.LeftToRight)
        weather_form.setStyleSheet("QWidget {\n"
"    background-color:#04B0FB;\n"
"}")
        self.inputCity = QtWidgets.QLineEdit(weather_form)
        self.inputCity.setGeometry(QtCore.QRect(50, 30, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Gotham Pro")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.inputCity.setFont(font)
        self.inputCity.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.inputCity.setAcceptDrops(False)
        self.inputCity.setStyleSheet("QLineEdit {\n"
"    background-color: /*#B8CCD5*/#FCFAF7;\n"
"    /*border: 1px solid rgb(0, 85, 255);*/\n"
"    border-radius: 3px;\n"
"    color: #727173;\n"
"    font: 16pt \"Gotham Pro\";\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid #727173;\n"
"}")
        self.inputCity.setInputMethodHints(QtCore.Qt.ImhNone)
        self.inputCity.setInputMask("")
        self.inputCity.setFrame(True)
        self.inputCity.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.inputCity.setDragEnabled(False)
        self.inputCity.setReadOnly(False)
        self.inputCity.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.inputCity.setClearButtonEnabled(False)
        self.inputCity.setObjectName("inputCity")
        self.buttonGet = QtWidgets.QPushButton(weather_form)
        self.buttonGet.setGeometry(QtCore.QRect(130, 80, 111, 31))
        self.buttonGet.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.buttonGet.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.buttonGet.setAutoFillBackground(False)
        self.buttonGet.setStyleSheet("QPushButton {\n"
"    background-color: /*#B8CCD5*/#FCFAF7;\n"
"    border-radius: 3px;\n"
"    color: #727173;\n"
"    font: 12pt \"Gotham Pro\";\n"
"    padding-left: 6px;\n"
"    padding-right: 6px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: 1px solid #727173;\n"
"}")
        self.buttonGet.setInputMethodHints(QtCore.Qt.ImhNone)
        self.buttonGet.setCheckable(False)
        self.buttonGet.setAutoRepeat(False)
        self.buttonGet.setAutoExclusive(False)
        self.buttonGet.setAutoRepeatDelay(304)
        self.buttonGet.setObjectName("buttonGet")
        self.text_weather_in_city = QtWidgets.QLabel(weather_form)
        self.text_weather_in_city.setGeometry(QtCore.QRect(10, 120, 351, 21))
        self.text_weather_in_city.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    font: 12pt \"Gotham Pro Narrow\";\n"
"}\n"
"")
        self.text_weather_in_city.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.text_weather_in_city.setFrameShadow(QtWidgets.QFrame.Plain)
        self.text_weather_in_city.setTextFormat(QtCore.Qt.AutoText)
        self.text_weather_in_city.setScaledContents(False)
        self.text_weather_in_city.setAlignment(QtCore.Qt.AlignCenter)
        self.text_weather_in_city.setWordWrap(False)
        self.text_weather_in_city.setObjectName("text_weather_in_city")
        self.text_temp = QtWidgets.QLabel(weather_form)
        self.text_temp.setGeometry(QtCore.QRect(10, 190, 351, 51))
        self.text_temp.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    font: 44pt \"Gotham Pro Narrow\";\n"
"}\n"
"")
        self.text_temp.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.text_temp.setFrameShadow(QtWidgets.QFrame.Plain)
        self.text_temp.setTextFormat(QtCore.Qt.AutoText)
        self.text_temp.setScaledContents(False)
        self.text_temp.setAlignment(QtCore.Qt.AlignCenter)
        self.text_temp.setWordWrap(False)
        self.text_temp.setObjectName("text_temp")
        self.text_description = QtWidgets.QLabel(weather_form)
        self.text_description.setGeometry(QtCore.QRect(10, 140, 351, 51))
        self.text_description.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    font: 25px \"Gotham Pro Narrow\";\n"
"}\n"
"")
        self.text_description.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.text_description.setFrameShadow(QtWidgets.QFrame.Plain)
        self.text_description.setTextFormat(QtCore.Qt.AutoText)
        self.text_description.setScaledContents(False)
        self.text_description.setAlignment(QtCore.Qt.AlignCenter)
        self.text_description.setWordWrap(False)
        self.text_description.setObjectName("text_description")
        self.text_temp_likes = QtWidgets.QLabel(weather_form)
        self.text_temp_likes.setGeometry(QtCore.QRect(10, 240, 351, 41))
        self.text_temp_likes.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    font: 24px \"Gotham Pro Narrow\";\n"
"}\n"
"")
        self.text_temp_likes.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.text_temp_likes.setFrameShadow(QtWidgets.QFrame.Plain)
        self.text_temp_likes.setTextFormat(QtCore.Qt.AutoText)
        self.text_temp_likes.setScaledContents(False)
        self.text_temp_likes.setAlignment(QtCore.Qt.AlignCenter)
        self.text_temp_likes.setWordWrap(False)
        self.text_temp_likes.setObjectName("text_temp_likes")
        self.text_pressure = QtWidgets.QLabel(weather_form)
        self.text_pressure.setGeometry(QtCore.QRect(10, 280, 351, 31))
        self.text_pressure.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    font: 12pt \"Gotham Pro Narrow\";\n"
"}\n"
"")
        self.text_pressure.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.text_pressure.setFrameShadow(QtWidgets.QFrame.Plain)
        self.text_pressure.setTextFormat(QtCore.Qt.AutoText)
        self.text_pressure.setScaledContents(False)
        self.text_pressure.setAlignment(QtCore.Qt.AlignCenter)
        self.text_pressure.setWordWrap(False)
        self.text_pressure.setObjectName("text_pressure")
        self.text_humidity = QtWidgets.QLabel(weather_form)
        self.text_humidity.setGeometry(QtCore.QRect(10, 310, 351, 20))
        self.text_humidity.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    font: 12pt \"Gotham Pro Narrow\";\n"
"}\n"
"")
        self.text_humidity.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.text_humidity.setFrameShadow(QtWidgets.QFrame.Plain)
        self.text_humidity.setTextFormat(QtCore.Qt.AutoText)
        self.text_humidity.setScaledContents(False)
        self.text_humidity.setAlignment(QtCore.Qt.AlignCenter)
        self.text_humidity.setWordWrap(False)
        self.text_humidity.setObjectName("text_humidity")
        self.text_speed_wind = QtWidgets.QLabel(weather_form)
        self.text_speed_wind.setGeometry(QtCore.QRect(10, 330, 351, 20))
        self.text_speed_wind.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    font: 12pt \"Gotham Pro Narrow\";\n"
"}\n"
"")
        self.text_speed_wind.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.text_speed_wind.setFrameShadow(QtWidgets.QFrame.Plain)
        self.text_speed_wind.setTextFormat(QtCore.Qt.AutoText)
        self.text_speed_wind.setScaledContents(False)
        self.text_speed_wind.setAlignment(QtCore.Qt.AlignCenter)
        self.text_speed_wind.setWordWrap(False)
        self.text_speed_wind.setObjectName("text_speed_wind")
        self.text_direction_wind = QtWidgets.QLabel(weather_form)
        self.text_direction_wind.setGeometry(QtCore.QRect(10, 350, 351, 20))
        self.text_direction_wind.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    font: 12pt \"Gotham Pro Narrow\";\n"
"}\n"
"")
        self.text_direction_wind.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.text_direction_wind.setFrameShadow(QtWidgets.QFrame.Plain)
        self.text_direction_wind.setTextFormat(QtCore.Qt.AutoText)
        self.text_direction_wind.setScaledContents(False)
        self.text_direction_wind.setAlignment(QtCore.Qt.AlignCenter)
        self.text_direction_wind.setWordWrap(False)
        self.text_direction_wind.setObjectName("text_direction_wind")
        self.block_snow = QtWidgets.QGroupBox(weather_form)
        self.block_snow.setGeometry(QtCore.QRect(20, 380, 81, 51))
        self.block_snow.setStyleSheet("QGroupBox {\n"
"    color:white;\n"
"    font: 14px \"Gotham Pro Medium\";\n"
"}")
        self.block_snow.setAlignment(QtCore.Qt.AlignCenter)
        self.block_snow.setObjectName("block_snow")
        self.text_snow_hour = QtWidgets.QLabel(self.block_snow)
        self.text_snow_hour.setGeometry(QtCore.QRect(10, 18, 62, 11))
        self.text_snow_hour.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    font: 10pt \"Gotham Pro Narrow\";\n"
"}\n"
"")
        self.text_snow_hour.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.text_snow_hour.setFrameShadow(QtWidgets.QFrame.Plain)
        self.text_snow_hour.setTextFormat(QtCore.Qt.AutoText)
        self.text_snow_hour.setScaledContents(False)
        self.text_snow_hour.setAlignment(QtCore.Qt.AlignCenter)
        self.text_snow_hour.setWordWrap(False)
        self.text_snow_hour.setObjectName("text_snow_hour")
        self.text_snow_3_hour = QtWidgets.QLabel(self.block_snow)
        self.text_snow_3_hour.setGeometry(QtCore.QRect(10, 32, 62, 11))
        self.text_snow_3_hour.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    font: 10pt \"Gotham Pro Narrow\";\n"
"}\n"
"")
        self.text_snow_3_hour.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.text_snow_3_hour.setFrameShadow(QtWidgets.QFrame.Plain)
        self.text_snow_3_hour.setTextFormat(QtCore.Qt.AutoText)
        self.text_snow_3_hour.setScaledContents(False)
        self.text_snow_3_hour.setAlignment(QtCore.Qt.AlignCenter)
        self.text_snow_3_hour.setWordWrap(False)
        self.text_snow_3_hour.setObjectName("text_snow_3_hour")
        self.groupBox_2 = QtWidgets.QGroupBox(weather_form)
        self.groupBox_2.setGeometry(QtCore.QRect(270, 380, 81, 51))
        self.groupBox_2.setStyleSheet("QGroupBox {\n"
"    color:white;\n"
"    font: 14px \"Gotham Pro Medium\";\n"
"}")
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.text_rain_hour = QtWidgets.QLabel(self.groupBox_2)
        self.text_rain_hour.setGeometry(QtCore.QRect(10, 18, 62, 11))
        self.text_rain_hour.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    font: 10pt \"Gotham Pro Narrow\";\n"
"}\n"
"")
        self.text_rain_hour.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.text_rain_hour.setFrameShadow(QtWidgets.QFrame.Plain)
        self.text_rain_hour.setTextFormat(QtCore.Qt.AutoText)
        self.text_rain_hour.setScaledContents(False)
        self.text_rain_hour.setAlignment(QtCore.Qt.AlignCenter)
        self.text_rain_hour.setWordWrap(False)
        self.text_rain_hour.setObjectName("text_rain_hour")
        self.text_rain_3_hour = QtWidgets.QLabel(self.groupBox_2)
        self.text_rain_3_hour.setGeometry(QtCore.QRect(10, 32, 62, 11))
        self.text_rain_3_hour.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    font: 10pt \"Gotham Pro Narrow\";\n"
"}\n"
"")
        self.text_rain_3_hour.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.text_rain_3_hour.setFrameShadow(QtWidgets.QFrame.Plain)
        self.text_rain_3_hour.setTextFormat(QtCore.Qt.AutoText)
        self.text_rain_3_hour.setScaledContents(False)
        self.text_rain_3_hour.setAlignment(QtCore.Qt.AlignCenter)
        self.text_rain_3_hour.setWordWrap(False)
        self.text_rain_3_hour.setObjectName("text_rain_3_hour")
        self.block_sunrise_and_sunset = QtWidgets.QGroupBox(weather_form)
        self.block_sunrise_and_sunset.setGeometry(QtCore.QRect(110, 380, 151, 51))
        self.block_sunrise_and_sunset.setStyleSheet("QGroupBox {\n"
"    color:white;\n"
"    font: 14px \"Gotham Pro Medium\";\n"
"}")
        self.block_sunrise_and_sunset.setAlignment(QtCore.Qt.AlignCenter)
        self.block_sunrise_and_sunset.setObjectName("block_sunrise_and_sunset")
        self.text_sunrise = QtWidgets.QLabel(self.block_sunrise_and_sunset)
        self.text_sunrise.setGeometry(QtCore.QRect(11, 18, 131, 11))
        self.text_sunrise.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    font: 10pt \"Gotham Pro Narrow\";\n"
"}\n"
"")
        self.text_sunrise.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.text_sunrise.setFrameShadow(QtWidgets.QFrame.Plain)
        self.text_sunrise.setTextFormat(QtCore.Qt.AutoText)
        self.text_sunrise.setScaledContents(False)
        self.text_sunrise.setAlignment(QtCore.Qt.AlignCenter)
        self.text_sunrise.setWordWrap(False)
        self.text_sunrise.setObjectName("text_sunrise")
        self.text_sunset = QtWidgets.QLabel(self.block_sunrise_and_sunset)
        self.text_sunset.setGeometry(QtCore.QRect(11, 32, 131, 11))
        self.text_sunset.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    font: 10pt \"Gotham Pro Narrow\";\n"
"}\n"
"")
        self.text_sunset.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.text_sunset.setFrameShadow(QtWidgets.QFrame.Plain)
        self.text_sunset.setTextFormat(QtCore.Qt.AutoText)
        self.text_sunset.setScaledContents(False)
        self.text_sunset.setAlignment(QtCore.Qt.AlignCenter)
        self.text_sunset.setWordWrap(False)
        self.text_sunset.setObjectName("text_sunset")
        self.button_close = QtWidgets.QPushButton(weather_form)
        self.button_close.setGeometry(QtCore.QRect(349, 2, 20, 20))
        self.button_close.setStyleSheet("QPushButton {\n"
"    border:none;\n"
"    font: 10pt \"Arial Black\";\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid red;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: 2px solid red;\n"
"    color: red;\n"
"}")
        self.button_close.setCheckable(False)
        self.button_close.setDefault(True)
        self.button_close.setFlat(True)
        self.button_close.setObjectName("button_close")

        self.retranslateUi(weather_form)
        QtCore.QMetaObject.connectSlotsByName(weather_form)

    def retranslateUi(self, weather_form):
        _translate = QtCore.QCoreApplication.translate
        weather_form.setWindowTitle(_translate("weather_form", "Form"))
        self.inputCity.setPlaceholderText(_translate("weather_form", "Введите город"))
        self.buttonGet.setText(_translate("weather_form", "Получить"))
        self.text_weather_in_city.setText(_translate("weather_form", "Погода Александровск-Сахалинский"))
        self.text_temp.setText(_translate("weather_form", "56° C"))
        self.text_description.setText(_translate("weather_form", "ОБЛАЧНО С ПРОЯСНЕНИЯМИ"))
        self.text_temp_likes.setText(_translate("weather_form", "По ощущениям 78° C"))
        self.text_pressure.setText(_translate("weather_form", "Атмосферное давление 749 мм рт. ст."))
        self.text_humidity.setText(_translate("weather_form", "Влажность 33 %"))
        self.text_speed_wind.setText(_translate("weather_form", "Скорость ветра 34 м/с"))
        self.text_direction_wind.setText(_translate("weather_form", "Направление ветра ЮЮВ"))
        self.block_snow.setTitle(_translate("weather_form", "СНЕГ"))
        self.text_snow_hour.setText(_translate("weather_form", "112 мм/час"))
        self.text_snow_3_hour.setText(_translate("weather_form", "112 мм/3ч"))
        self.groupBox_2.setTitle(_translate("weather_form", "Дождь"))
        self.text_rain_hour.setText(_translate("weather_form", "112 мм/час"))
        self.text_rain_3_hour.setText(_translate("weather_form", "112 мм/3ч"))
        self.block_sunrise_and_sunset.setTitle(_translate("weather_form", "Восход-Закат"))
        self.text_sunrise.setText(_translate("weather_form", "Восход в 06.55"))
        self.text_sunset.setText(_translate("weather_form", "Закат в 18.44"))
        self.button_close.setText(_translate("weather_form", "X"))
